version: '3'

services:

###########################
# Setup for backend container
###########################
  backend:
    build: ./backend
    expose: 
      - "8080"
    ports:
      - "8080:8080"
    volumes:
      - ./backend/src:/app/src
    command: npm run start

###########################
# Setup for frontend container
###########################
  frontend:
    build: ./frontend
    expose: 
      - "3000"
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    links:
      - backend
    command: npm run start